<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembayaran_model extends CI_Model
{

    public $table = 'pembayaran';
    public $id = 'id_pembayaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    { $this->db->select('id_pembayaran, id_pemesan,pemesan.Nama, id_barang, tgl_pemesanan', 'total_harga');
       /* $this->db->join('barang', 'barang.id_barang = pembayaran.id_barang', 'left');
      */  $this->db->join('pemesan', 'pemesan.id_pemesan = pembayaran.id_pemesan', 'left');

        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {/*$this->db->join('barang', 'barang.id_barang = pembayaran.id_barang', 'left');
        $this->db->join('pemesan', 'pemesan.id_pemesan = pembayaran.id_pemesan', 'left');
*/
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
/*
        $this->db->join('barang','barang.id_barang=pembayaran.id_barang');
 */
        $this->db->join('pemesan','pemesan.id_pemesan=pembayaran.id_pemesan');
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
     /*   $this->db->join('barang','barang.id_barang=pembayaran.id_barang');
 */       $this->db->join('pemesan','pemesan.id_pemesan=pembayaran.id_pemesan');

        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data,$data2)
    {     
  
    $this->db->insert($this->table, $data);
    
    
    $this->db->where('id_barang', $data2['id_barang']);
    $cari = $this->db->get('barang')->row();

    $pengurangan = array(
        'M' => $cari->M - $data2['M'],
        'L' => $cari->L - $data2['L'],
        'XL' => $cari->XL - $data2['XL'],
        'XXL' => $cari->XXL - $data2['XXL'],
        'XXXL' => $cari->XXXL - $data2['XXXL']

     );
    $this->db->where('id_barang',$data['id_barang']);
    $this->db->update('barang',$pengurangan);
    /*die(print_r($cari));*/
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pembayaran_model.php */
/* Location: ./application/models/Pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-31 16:25:17 */
/* http://harviacode.com */